name: Solve Problem Section 3
on: push
jobs:
  step-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Dependencies
        run: cd problem-section-3 && npm ci
      - name: Lint
        run: cd problem-section-3 && npm run lint
      - name: Test
        run: cd problem-section-3 && npm run test
      - name: Build
        run: cd problem-section-3 && npm run build